/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuiportalapplication.Screens;
import com.formdev.flatlaf.intellijthemes.FlatHiberbeeDarkIJTheme;
import cuiportalapplication.*;
import cuiportalapplication.codes.CommonCodes;
/**
 *
 * @author LENOVO
 */
public class AdminMenuScreen extends javax.swing.JFrame {
    private String thisScreenOwner;
    /**
     * Creates new form AdminMenuScreen
     */
    public AdminMenuScreen() {
        initComponents();
        thisScreenOwner="admin";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnViewQuizMarks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCreateStudentProfile = new javax.swing.JButton();
        btnViewStudentProfile = new javax.swing.JButton();
        btnCreateTeacherProfile = new javax.swing.JButton();
        btnViewTeacherProfile = new javax.swing.JButton();
        btnTheme = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnDeleteTeacher = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnViewQuizMarks.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnViewQuizMarks.setText("View Quiz Marks");
        BtnViewQuizMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewQuizMarksActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        btnCreateStudentProfile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCreateStudentProfile.setText("Create Student Profile");
        btnCreateStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentProfileActionPerformed(evt);
            }
        });

        btnViewStudentProfile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewStudentProfile.setText("View Student Profile");
        btnViewStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentProfileActionPerformed(evt);
            }
        });

        btnCreateTeacherProfile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCreateTeacherProfile.setText("Create Teacher Profile");
        btnCreateTeacherProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTeacherProfileActionPerformed(evt);
            }
        });

        btnViewTeacherProfile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewTeacherProfile.setText("View Teacher Profile");
        btnViewTeacherProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTeacherProfileActionPerformed(evt);
            }
        });

        btnTheme.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTheme.setText("Change Theme");
        btnTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemeActionPerformed(evt);
            }
        });

        btnDeleteStudent.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDeleteStudent.setText("Delete Student");
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnDeleteTeacher.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDeleteTeacher.setText("Delete Teacher");
        btnDeleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeacherActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(204, 0, 0));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnViewQuizMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnViewStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewTeacherProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCreateStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnCreateTeacherProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateTeacherProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewTeacherProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnViewQuizMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentProfileActionPerformed
        // TODO add your handling code here:
        PersonalInfoScreenInput frame=new PersonalInfoScreenInput("student",thisScreenOwner);
        dispose();
        frame.setVisible(true);
       
    }//GEN-LAST:event_btnCreateStudentProfileActionPerformed

    private void btnCreateTeacherProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTeacherProfileActionPerformed

        PersonalInfoScreenInput frame=new PersonalInfoScreenInput("teacher",thisScreenOwner);
        dispose();
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_btnCreateTeacherProfileActionPerformed

    private void btnViewStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentProfileActionPerformed
        // TODO add your handling code here:
        
        dispose();
        PersonSearchScreen.personRole="student";
        PersonSearchScreen frame=new PersonSearchScreen(thisScreenOwner);
        
        
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnViewStudentProfileActionPerformed

    private void btnViewTeacherProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTeacherProfileActionPerformed
        // TODO add your handling code here:
        dispose();
        PersonSearchScreen.personRole="teacher";
        PersonSearchScreen frame=new PersonSearchScreen(thisScreenOwner);
         
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnViewTeacherProfileActionPerformed

    private void btnThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemeActionPerformed
        // TODO add your handling code here:
        CommonCodes.selectThemeOptionPane();
        dispose();
        AdminMenuScreen frame=new AdminMenuScreen();
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnThemeActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        // TODO add your handling code here:
        dispose();
        DeletePerson frame=new DeletePerson("student",thisScreenOwner);
        frame.setVisible(true);
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTeacherActionPerformed
        // TODO add your handling code here:
        dispose();
        DeletePerson frame=new DeletePerson("teacher",thisScreenOwner);
        frame.setVisible(true);
    }//GEN-LAST:event_btnDeleteTeacherActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        dispose();
        LogInScreen frame=new LogInScreen();
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void BtnViewQuizMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewQuizMarksActionPerformed
        // TODO add your handling code here:
        dispose();
        ViewQuizMarks frame=new ViewQuizMarks(thisScreenOwner);
        frame.setVisible(true);
        
    }//GEN-LAST:event_BtnViewQuizMarksActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnViewQuizMarks;
    private javax.swing.JButton btnCreateStudentProfile;
    private javax.swing.JButton btnCreateTeacherProfile;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnDeleteTeacher;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnTheme;
    private javax.swing.JButton btnViewStudentProfile;
    private javax.swing.JButton btnViewTeacherProfile;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
