/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuiportalapplication.Screens;
import cuiportalapplication.codes.*;
import cuiportalapplication.users.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RANAA
 */
public class PersonSearchScreen extends javax.swing.JFrame {
    String role1;
    String role2;
    private String caller;
    private DefaultTableModel model;
    public static String personRole="";
    /**
     * Creates new form PersonSearchScreen
     */
    public PersonSearchScreen(String cal) {
        
        initComponents();
        this.caller=cal;
        
        
        if(personRole.equals("student")){
            
            lblHeading.setText("Search Student");
             role1="Semester";
            role2="Program";
        }else{
            lblHeading.setText("Search Teacher");
            role1="Qualification";
            role2="Subject of Teaching";
        }
        System.out.println(personRole+"  helooo");
        model = (DefaultTableModel) tablePersonDetails.getModel();
        model.setColumnIdentifiers(new String[]{"ID", "Name", role1, role2});
        
        
    }

    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        lblHeading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        radioById = new javax.swing.JRadioButton();
        radioViewAll = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePersonDetails = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeading.setText("Search");
        lblHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Enter ID");

        buttonGroup1.add(radioById);
        radioById.setSelected(true);
        radioById.setText("By ID");
        radioById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioByIdActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioViewAll);
        radioViewAll.setText("View All");
        radioViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioViewAllActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tablePersonDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePersonDetails);

        lblStatus.setText("Status : ");

        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioById)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioViewAll))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioById)
                    .addComponent(radioViewAll))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnMainMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioViewAllActionPerformed
        // TODO add your handling code here:
        if(radioViewAll.isSelected()){
            model.setRowCount(0);
            txtId.setEnabled(false);
            btnSearch.setEnabled(false);
        }
        if(personRole.equals("student")){
            ArrayList<Student> allData=new ArrayList<>();
            allData=FileHandling.readCompleteFile(Student.class);
            for(Student s1:allData){
                 model.addRow(new String[]{s1.getId(), s1.getName(), s1.getSemester(), s1.getProgram()});
            }
        }
        else{
             ArrayList<Teacher> allData=new ArrayList<>();
            allData=FileHandling.readCompleteFile(Teacher.class);
            for(Teacher t1:allData){
                  model.addRow(new String[]{t1.getId(),t1.getName(),t1.getQualification(),t1.getSubjectToTeach()});
            }
        }
    }//GEN-LAST:event_radioViewAllActionPerformed

    private void radioByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioByIdActionPerformed
        // TODO add your handling code here:
        if(radioById.isSelected()){
            txtId.setEnabled(true);
        }
    }//GEN-LAST:event_radioByIdActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String id=txtId.getText();
        if(personRole.equals("student")){
            Student s1=FileHandling.findUsersObjectById(Student.class, id);
            if(s1==null){
                lblStatus.setText("No Data Found !");
            }
            else{
               model.addRow(new String[]{s1.getId(), s1.getName(), s1.getSemester(), s1.getProgram()});
            }
        }else{
            Teacher t1=FileHandling.findUsersObjectById(Teacher.class, id);
            if(t1==null){
                lblStatus.setText("No Data Found !");
            }
            else{
                model.addRow(new String[]{t1.getId(),t1.getName(),t1.getQualification(),t1.getSubjectToTeach()});
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
         if(caller.equalsIgnoreCase("admin")){
            dispose();
            AdminMenuScreen frame=new AdminMenuScreen();
            frame.setVisible(true);
        }else{
            dispose();
            TeacherMenuScreen frame=new TeacherMenuScreen();
            frame.setVisible(true);
        }
    }//GEN-LAST:event_btnMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonSearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonSearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonSearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonSearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonSearchScreen("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton radioById;
    private javax.swing.JRadioButton radioViewAll;
    public javax.swing.JTable tablePersonDetails;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
