/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuiportalapplication.Screens;
import cuiportalapplication.codes.*;
/**
 *
 * @author LENOVO
 */
public class TeacherMenuScreen extends javax.swing.JFrame {

    /**
     * Creates new form TeacherMenuScreen
     */
    private String thisScreenOwner;
    public TeacherMenuScreen() {
        initComponents();
        thisScreenOwner="teacher";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreateStudentProfile = new javax.swing.JButton();
        btnViewStudentProfile = new javax.swing.JButton();
        btnMarkAttendace = new javax.swing.JButton();
        btnCreateQuiz = new javax.swing.JButton();
        BtnViewQuizMarks = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnShowAttendence = new javax.swing.JButton();
        btnTheme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher");

        btnCreateStudentProfile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreateStudentProfile.setText("Create Student Profile");
        btnCreateStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentProfileActionPerformed(evt);
            }
        });

        btnViewStudentProfile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewStudentProfile.setText("View Student Profile");
        btnViewStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentProfileActionPerformed(evt);
            }
        });

        btnMarkAttendace.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMarkAttendace.setText("Mark Attendance");
        btnMarkAttendace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAttendaceActionPerformed(evt);
            }
        });

        btnCreateQuiz.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreateQuiz.setText("Create Quiz");
        btnCreateQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateQuizActionPerformed(evt);
            }
        });

        BtnViewQuizMarks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnViewQuizMarks.setText("View Quiz Marks");
        BtnViewQuizMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewQuizMarksActionPerformed(evt);
            }
        });

        btnViewProfile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnDeleteStudent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDeleteStudent.setText("Delete Student");
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnShowAttendence.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnShowAttendence.setText("Show Attendance");
        btnShowAttendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAttendenceActionPerformed(evt);
            }
        });

        btnTheme.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTheme.setText("Change Theme");
        btnTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCreateStudentProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(btnViewStudentProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnMarkAttendace, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowAttendence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnViewQuizMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnMarkAttendace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowAttendence, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnViewQuizMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateQuizActionPerformed
        // TODO add your handling code here:
        dispose();
        String subject=CommonCodes.globalTeacherObject.getSubjectToTeach();
        CreateQuizScreen frame=new CreateQuizScreen(subject);
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnCreateQuizActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        ViewProfileScreen obj=new ViewProfileScreen("teacher");
        dispose();
         
        
        obj.setVisible(true);
        obj.setValues(CommonCodes.globalTeacherObject);
       
        
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnCreateStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentProfileActionPerformed
        // TODO add your handling code here:

        PersonalInfoScreenInput frame=new PersonalInfoScreenInput("student",thisScreenOwner);
        dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_btnCreateStudentProfileActionPerformed

    private void btnViewStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentProfileActionPerformed
        // TODO add your handling code here:
        dispose();
        PersonSearchScreen.personRole="student";
        PersonSearchScreen frame=new PersonSearchScreen(thisScreenOwner);
        
        frame.setVisible(true);
    }//GEN-LAST:event_btnViewStudentProfileActionPerformed

    private void btnMarkAttendaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAttendaceActionPerformed
        // TODO add your handling code here:
        dispose();
        AttendenceScreen frame=new AttendenceScreen("student");
        frame.setVisible(true);
    }//GEN-LAST:event_btnMarkAttendaceActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        dispose();
        LogInScreen frame=new LogInScreen();
        frame.setVisible(true);

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        // TODO add your handling code here:
        dispose();
        DeletePerson frame=new DeletePerson("student",thisScreenOwner);
        frame.setVisible(true);
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void BtnViewQuizMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewQuizMarksActionPerformed
        // TODO add your handling code here:
        dispose();
        ViewQuizMarks frame=new ViewQuizMarks(thisScreenOwner);
        frame.setVisible(true);
    }//GEN-LAST:event_BtnViewQuizMarksActionPerformed

    private void btnShowAttendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAttendenceActionPerformed
        // TODO add your handling code here:
        dispose();
        ShowAttendence frame=new ShowAttendence("student",thisScreenOwner);
        frame.setVisible(true);
    }//GEN-LAST:event_btnShowAttendenceActionPerformed

    private void btnThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemeActionPerformed
        // TODO add your handling code here:
        CommonCodes.selectThemeOptionPane();
        dispose();
        AdminMenuScreen frame=new AdminMenuScreen();
        frame.setVisible(true);

    }//GEN-LAST:event_btnThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherMenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnViewQuizMarks;
    private javax.swing.JButton btnCreateQuiz;
    private javax.swing.JButton btnCreateStudentProfile;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMarkAttendace;
    private javax.swing.JButton btnShowAttendence;
    private javax.swing.JButton btnTheme;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JButton btnViewStudentProfile;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
