/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuiportalapplication.Screens;
import cuiportalapplication.codes.*;

import cuiportalapplication.users.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RANAA
 */
public class ViewQuizMarks extends javax.swing.JFrame {
    
    private String caller;
    private DefaultTableModel model;
    private String subject;
    Student studentObject;
    boolean foundStaus=false;
    /**
     * Creates new form ViewQuizMarks
     */
    public ViewQuizMarks(String cal) {
        initComponents();
        this.caller=cal;
        if(caller.equalsIgnoreCase("student")){
            setSubjects();
            panelForAdminTeacher.hide();
        }else{
           
            comboSetSubjects.setEnabled(false);
            btnSearch.setEnabled(false);
            radioReset.hide();
        }
    }
    public void setSubjects(){
        comboSetSubjects.removeAllItems();
        studentObject=CommonCodes.globalStudentObject;
        String [] subjects=studentObject.getSubjects();
        for(String s:subjects){
            comboSetSubjects.addItem(s);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectSubject = new javax.swing.JLabel();
        comboSetSubjects = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetails = new javax.swing.JTable();
        btnMainMenu = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        panelForAdminTeacher = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        radioReset = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSelectSubject.setText("Select Subject");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tableDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Semester", "Subject", "Marks"
            }
        ));
        jScrollPane1.setViewportView(tableDetails);

        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        lblStatus.setText("Status :");

        jLabel1.setText("Enter ID");

        lblName.setText("Name ");

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        radioReset.setBackground(new java.awt.Color(153, 0, 0));
        radioReset.setForeground(new java.awt.Color(255, 255, 255));
        radioReset.setText("Reset");
        radioReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelForAdminTeacherLayout = new javax.swing.GroupLayout(panelForAdminTeacher);
        panelForAdminTeacher.setLayout(panelForAdminTeacherLayout);
        panelForAdminTeacherLayout.setHorizontalGroup(
            panelForAdminTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForAdminTeacherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelForAdminTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelForAdminTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblName)
                        .addComponent(jLabel1)
                        .addComponent(txtId)
                        .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addComponent(radioReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelForAdminTeacherLayout.setVerticalGroup(
            panelForAdminTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForAdminTeacherLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(radioReset)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panelForAdminTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSetSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSelectSubject)
                                .addComponent(comboSetSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMainMenu)
                            .addComponent(lblStatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panelForAdminTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public boolean findStudent(){
        String id=txtId.getText();
        studentObject=FileHandling.findUsersObjectById(Student.class, id);
        if(studentObject==null){
            lblStatus.setText("No Data Found");
            return false;
        }else{
            lblName.setText(studentObject.getName());
            comboSetSubjects.removeAllItems();
            String [] subjects=studentObject.getSubjects();
            for(String s:subjects){
                System.out.println("Length -----------"+subjects.length);
                comboSetSubjects.addItem(s);
            }
        }
        return true;
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
            model = (DefaultTableModel) tableDetails.getModel();
            model.setRowCount(0);
            
            
           String id;
            String name;
            String semester;
            ArrayList<Marks> allMarksOfSubject;
        if(caller.equals("student")){
            
            subject=comboSetSubjects.getSelectedItem().toString();
           id=studentObject.getId();
             name=studentObject.getName();
             semester=studentObject.getSemester();
             allMarksOfSubject=studentObject.getMarksOfSubject(subject);
            if(allMarksOfSubject.size()!=0){
                lblStatus.setText("You Attempted Total "+allMarksOfSubject.size()+" Quiz");
                for(Marks marksInOneQuiz:allMarksOfSubject){
                    String marks=String.valueOf(marksInOneQuiz.getMarks());

                    model.addRow(new String []{id,name,semester,subject,marks});
                }
            }else{
                lblStatus.setText("No Data For "+subject);
            }
        }else{
                
                
                comboSetSubjects.setEnabled(true);
                
                subject=comboSetSubjects.getSelectedItem().toString();
                id=studentObject.getId();
                 name=studentObject.getName();
                 semester=studentObject.getSemester();
                 allMarksOfSubject=studentObject.getMarksOfSubject(subject);
                if(allMarksOfSubject.size()!=0){
                    lblStatus.setText("You Attempted Total "+allMarksOfSubject.size()+" Quiz");
                    for(Marks marksInOneQuiz:allMarksOfSubject){
                        String marks=String.valueOf(marksInOneQuiz.getMarks());

                        model.addRow(new String []{id,name,semester,subject,marks});
                    }
                }else{
                    lblStatus.setText("No Data For "+subject);
                }
            }
            
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        if(caller.equalsIgnoreCase("admin")){
            dispose();
            AdminMenuScreen frame=new AdminMenuScreen();
            frame.setVisible(true);
        }else if(caller.equalsIgnoreCase("student")){
            dispose();
            StudentMenuScreen frame=new StudentMenuScreen();
            frame.setVisible(true);
        }
        else{
            dispose();
            TeacherMenuScreen frame=new TeacherMenuScreen();
            frame.setVisible(true);
        }
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        if(txtId.getText().length()==0){
                lblStatus.setText("Enter ID please");
        }else if(findStudent()){
            radioReset.setVisible(true);
            txtId.setEnabled(false);
            foundStaus=true;
            btnSearch.setEnabled(true);
            comboSetSubjects.setEnabled(true);
           
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void radioResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioResetActionPerformed
        // TODO add your handling code here:
        dispose();
        ViewQuizMarks frame=new ViewQuizMarks(caller);
        frame.setVisible(true);
    }//GEN-LAST:event_radioResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuizMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuizMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuizMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuizMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuizMarks("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboSetSubjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSelectSubject;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel panelForAdminTeacher;
    private javax.swing.JRadioButton radioReset;
    private javax.swing.JTable tableDetails;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
